import Head from 'next/head'
import Image from 'next/image'
import Nav from '../components/Nav'
import Header from '../components/Header'
import Results from '../components/Results'
import requests from '../utils/requests'
export default function Home({results}) {
  console.log(results)
  return (
    <div>
      <Head>
        <title>hulu 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* header */} 
      <Header/>
      {/* Nav */}
      <Nav/>
      {/* Results */}
      <Results requests={results}/>
    </div>  
  )
}

export async function getServerSideProps(context){
  const genre=context.query.genre;

  const request=await fetch(`https://api.themoviedb.org/3${requests[genre]?.url || requests.fetchTrending.url}`)
  .then((res)=>res.json())
  return{
   props:{   
     results:request.results,
   }
  } 
} 
 